### ISSUE TITLE
Terralith Incompatiblilty?

### ISSUE THREAD

**Issue by Gantros** [Quidvio/No-Caves-World-Generation#1]
I'm using the 1.20.x version of Retro Caves and it had the side effect of altering some of the Terralith Biomes, most noticeably the Volcanic Peaks and Craters which have gone from being blackstone to being regular stone with a grass block topping. Also, for Volcanic Craters specifically, the pool of lava that is supposed to be present has been reduced to a few sourceblocks that don't flow. Is there a way you could fix compatibility for mods like Terralith, Tectonic, and WWOO?

**Comment by klinbee** [comment]
I would first try re-ordering the datapacks in the datapack folder (like if you put mine on top, lower it's priority). If that doesn't work, the main way I would need to add compatibility is copy the surface rules for Terralith/Tectonic/WWOO. 

I don't plan on doing that though because I'm busy with other things and there isn't enough incentive at the moment.

**Comment by Gantros** [comment]
OK I'll give it a try and get back to you.

**Comment by Gantros** [comment]
I do have a question: If I use the Terralith and WWOO mods, which would take priority when the datapacks are applied? Would I have to switch to the datapack versions of both?

**Comment by klinbee** [comment]
When you use the mods, they should just inject their datapacks into the datapack folder. You should not need to switch to the datapack versions because the mod just injects the datapack.

**Comment by Gantros** [comment]
So, then when I apply the datapack, it takes lower priority than the .jar mods?

**Comment by klinbee** [comment]
Yeah nevermind what I was saying. It's probably not going to work and I think that's only something you can change on forge, because it actually shows you what datapacks it is adding.

**Comment by Gantros** [comment]
I'm running into problems anyway. When I remove Terralith and WWOO jars, the game crashes when I start a new world. It works again when I put them back.
