### ISSUE TITLE
Ship NoCaves as a mod too (on Modrinth)

### ISSUE THREAD

**Issue by vico93** [Quidvio/No-Caves-World-Generation#3]
I think Modrinth can auto-ship datapacks as mods if the owner allows to. At least a couple of datapacks (and datapack+resource pack combos) on that have a mod version as well, that's why i suspect it's a trivial task to do.

If not, it's just a matter of take the datapack .zip file, add a couple of "descriptor" files alongside `pack.mcmeta` (`fabric.mod.json` for Fabric, `mods.toml` for Forge and i don't know if NeoForge uses another separate file or `mods.toml` as well), then switch the extension from `.zip` to `.jar` and upload separately as a mod. A quick guide about this can be found in [this page](https://news.lunareclipse.studio/article/sotc-instant-datapack-mod-ports) from the From the Fog creators.

The reason about this request is that shipping a "mod version" would ease the initial configuration (for modded players, of course) of a new world and would de-clutter the datapack list, and also would spare the need to use mods like [Data Loader](https://modrinth.com/mod/dataloader) to setup datapacks automatically for each new world created.

Example of how it looks when a datapack in MR also ships the "mod version":
![image](https://github.com/Gamemode4Dev/GM4_Datapacks/assets/3485505/b8c465a1-e2c1-44f2-a687-178b8f9d245f)

**Comment by klinbee** [comment]
Tbh I was just lazy and figured that most people would just use the default (which I do have packaged as a mod). Idk if there's a fully automatic way (where I can just enable always package as mod) but I just went ahead and packaged the others as mods too. I'll probably do this with more of my data packs, but I hate how cluttered it gets with multiple data pack versions and mc versions.

I've done it though for all of the other ones as well now :P. I appreciate the input/helpful links.
