### ISSUE TITLE
Does it also remove mob spawners?

### ISSUE THREAD

**Issue by kotoshii** [Quidvio/No-Caves-World-Generation#4]
I noticed there are no mob spawners ([monster rooms](https://minecraft.fandom.com/wiki/Monster_Room)) with this datapack. Even in the places where I remember they actually generated before.
If it really removes mob spawner rooms, is there a way to bring them back?

**Comment by kotoshii** [comment]
Also, can you please suggest how I can modify the datapack to actually keep some amount of caves?
Let's say, 10% of the original amount.

**Comment by klinbee** [comment]
This question is kind of like saying "Hey, you've removed rivers from the world, does this also remove sugarcane?"

Monster spawners have a hard-coded (cannot be changed with data packs) spawn requirement needing air to be surrounding it's spawning location. The only way to do that is through caves or other structures. You'll see that they do spawn near Mineshafts and Strongholds.

**Comment by kotoshii** [comment]
Understand. Is it possible then to somehow bring back a small amount of caves?

> Also, can you please suggest how I can modify the datapack to actually keep some amount of caves?
Let's say, 10% of the original amount.

**Comment by klinbee** [comment]
> Understand. Is it possible then to somehow bring back a small amount of caves?
> 
> 
> 
> > Also, can you please suggest how I can modify the datapack to actually keep some amount of caves?
> 
> Let's say, 10% of the original amount.

Oh yeah. I would look on Misode's data pack generator for the default carver cave presets to see their default probabilities. Then, I'd adjust them to be 1/10th as much. (Literally a "probability" field in the carver cave files).

**Comment by kotoshii** [comment]
OK, thanks a lot!
